const fs = require('fs');
const path = require('path');

// Generate env.js from Vercel environment variables
const env = {
    SUPABASE_URL: process.env.SUPABASE_URL || '',
    SUPABASE_ANON_KEY: process.env.SUPABASE_ANON_KEY || '',
    SUPABASE_SERVICE_KEY: process.env.SUPABASE_SERVICE_KEY || '',
    BACKEND_URL: process.env.BACKEND_URL || '',
};

const content = `// Auto-generated by build script — DO NOT EDIT
const ENV = ${JSON.stringify(env, null, 4)};
`;

const outPath = path.join(__dirname, 'admin-panel', 'js', 'env.js');
fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, content);
console.log('✅ env.js generated');
